name: icaros
description: Um projeto que une seu smartphone ao seu computador.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  file_picker: ^5.2.2
  flutter_launcher_icons: ^0.11.0
  dart_ping: ^8.0.1
  network_info_plus: ^3.0.1
  dio: ^5.1.1

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "assets/icon/background.png" 
  adaptive_icon_foreground: "assets/icon/foreground.png "

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/youtube_logo.png
    - assets/icon/icon.png